# Triggers
name: triggers
run-name: triggers !!!

on:
  push:
    branches: [ "main" ]
    paths:
      - "main.js"

  workflow_dispatch:

jobs:
  Execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup env with Node
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 18
      - name: Run with main.js
        run: node reto1.js